name: Build masuperapp using Nix

on:
  push:
    branches: main

jobs:
  build-and-run:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.11

      - name: Build using Nix
        run: nix-build

